export const collections = [
  {
    id: 1,
    categoryName: "Fashion",
    urlSlug: "fashion",
    parentCategoryId: null,
    level: "COLLECTION",
    categoryImageUrl: "fashion.jpg",
    status: "ACTIVE",
    createdAt: "2024-08-25",
    updatedAt: null,
    subCategories: [
      {
        id: 2,
        categoryName: "Men's Clothing",
        urlSlug: "mens-clothing",
        parentCategoryId: 1,
        level: "CATEGORY",
        categoryImageUrl: "mens-clothing.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 3,
            categoryName: "T-Shirts",
            urlSlug: "t-shirts",
            parentCategoryId: 2,
            level: "SUB_CATEGORY",
            categoryImageUrl: "t-shirts.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 4,
            categoryName: "Shirts",
            urlSlug: "shirts",
            parentCategoryId: 2,
            level: "SUB_CATEGORY",
            categoryImageUrl: "shirts.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 5,
            categoryName: "Jeans",
            urlSlug: "jeans",
            parentCategoryId: 2,
            level: "SUB_CATEGORY",
            categoryImageUrl: "jeans.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 6,
            categoryName: "Jackets",
            urlSlug: "jackets",
            parentCategoryId: 2,
            level: "SUB_CATEGORY",
            categoryImageUrl: "jackets.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 7,
            categoryName: "Footwear",
            urlSlug: "footwear",
            parentCategoryId: 2,
            level: "SUB_CATEGORY",
            categoryImageUrl: "footwear.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 8,
        categoryName: "Women's Clothing",
        urlSlug: "womens-clothing",
        parentCategoryId: 1,
        level: "CATEGORY",
        categoryImageUrl: "womens-clothing.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 9,
            categoryName: "Dresses",
            urlSlug: "dresses",
            parentCategoryId: 8,
            level: "SUB_CATEGORY",
            categoryImageUrl: "dresses.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 10,
            categoryName: "Tops",
            urlSlug: "tops",
            parentCategoryId: 8,
            level: "SUB_CATEGORY",
            categoryImageUrl: "tops.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 11,
            categoryName: "Skirts",
            urlSlug: "skirts",
            parentCategoryId: 8,
            level: "SUB_CATEGORY",
            categoryImageUrl: "skirts.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 12,
            categoryName: "Footwear",
            urlSlug: "womens-footwear",
            parentCategoryId: 8,
            level: "SUB_CATEGORY",
            categoryImageUrl: "womens-footwear.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 13,
            categoryName: "Accessories",
            urlSlug: "womens-accessories",
            parentCategoryId: 8,
            level: "SUB_CATEGORY",
            categoryImageUrl: "womens-accessories.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 14,
        categoryName: "Kid's Clothing",
        urlSlug: "kids-clothing",
        parentCategoryId: 1,
        level: "CATEGORY",
        categoryImageUrl: "kids-clothing.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 15,
            categoryName: "T-Shirts",
            urlSlug: "kids-t-shirts",
            parentCategoryId: 14,
            level: "SUB_CATEGORY",
            categoryImageUrl: "kids-t-shirts.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 16,
            categoryName: "Shorts",
            urlSlug: "kids-shorts",
            parentCategoryId: 14,
            level: "SUB_CATEGORY",
            categoryImageUrl: "kids-shorts.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 17,
            categoryName: "Jeans",
            urlSlug: "kids-jeans",
            parentCategoryId: 14,
            level: "SUB_CATEGORY",
            categoryImageUrl: "kids-jeans.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 18,
            categoryName: "Footwear",
            urlSlug: "kids-footwear",
            parentCategoryId: 14,
            level: "SUB_CATEGORY",
            categoryImageUrl: "kids-footwear.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 19,
            categoryName: "Accessories",
            urlSlug: "kids-accessories",
            parentCategoryId: 14,
            level: "SUB_CATEGORY",
            categoryImageUrl: "kids-accessories.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
    ],
  },
  {
    id: 20,
    categoryName: "Home & Lifestyle",
    urlSlug: "home-lifestyle",
    parentCategoryId: null,
    level: "COLLECTION",
    categoryImageUrl: "home-lifestyle.jpg",
    status: "ACTIVE",
    createdAt: "2024-08-25",
    updatedAt: null,
    subCategories: [
      {
        id: 21,
        categoryName: "Furniture",
        urlSlug: "furniture",
        parentCategoryId: 20,
        level: "CATEGORY",
        categoryImageUrl: "furniture.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 22,
            categoryName: "Sofas",
            urlSlug: "sofas",
            parentCategoryId: 21,
            level: "SUB_CATEGORY",
            categoryImageUrl: "sofas.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 23,
            categoryName: "Beds",
            urlSlug: "beds",
            parentCategoryId: 21,
            level: "SUB_CATEGORY",
            categoryImageUrl: "beds.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 24,
            categoryName: "Dining Tables",
            urlSlug: "dining-tables",
            parentCategoryId: 21,
            level: "SUB_CATEGORY",
            categoryImageUrl: "dining-tables.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 25,
            categoryName: "Chairs",
            urlSlug: "chairs",
            parentCategoryId: 21,
            level: "SUB_CATEGORY",
            categoryImageUrl: "chairs.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 26,
            categoryName: "Wardrobes",
            urlSlug: "wardrobes",
            parentCategoryId: 21,
            level: "SUB_CATEGORY",
            categoryImageUrl: "wardrobes.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 27,
        categoryName: "Home Decor",
        urlSlug: "home-decor",
        parentCategoryId: 20,
        level: "CATEGORY",
        categoryImageUrl: "home-decor.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 28,
            categoryName: "Wall Art",
            urlSlug: "wall-art",
            parentCategoryId: 27,
            level: "SUB_CATEGORY",
            categoryImageUrl: "wall-art.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 29,
            categoryName: "Vases",
            urlSlug: "vases",
            parentCategoryId: 27,
            level: "SUB_CATEGORY",
            categoryImageUrl: "vases.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 30,
            categoryName: "Mirrors",
            urlSlug: "mirrors",
            parentCategoryId: 27,
            level: "SUB_CATEGORY",
            categoryImageUrl: "mirrors.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 31,
            categoryName: "Clocks",
            urlSlug: "clocks",
            parentCategoryId: 27,
            level: "SUB_CATEGORY",
            categoryImageUrl: "clocks.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 32,
            categoryName: "Rugs",
            urlSlug: "rugs",
            parentCategoryId: 27,
            level: "SUB_CATEGORY",
            categoryImageUrl: "rugs.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 33,
        categoryName: "Bedding",
        urlSlug: "bedding",
        parentCategoryId: 20,
        level: "CATEGORY",
        categoryImageUrl: "bedding.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 34,
            categoryName: "Bedsheets",
            urlSlug: "bedsheets",
            parentCategoryId: 33,
            level: "SUB_CATEGORY",
            categoryImageUrl: "bedsheets.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 35,
            categoryName: "Comforters",
            urlSlug: "comforters",
            parentCategoryId: 33,
            level: "SUB_CATEGORY",
            categoryImageUrl: "comforters.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 36,
            categoryName: "Pillows",
            urlSlug: "pillows",
            parentCategoryId: 33,
            level: "SUB_CATEGORY",
            categoryImageUrl: "pillows.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 37,
            categoryName: "Blankets",
            urlSlug: "blankets",
            parentCategoryId: 33,
            level: "SUB_CATEGORY",
            categoryImageUrl: "blankets.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 38,
            categoryName: "Mattresses",
            urlSlug: "mattresses",
            parentCategoryId: 33,
            level: "SUB_CATEGORY",
            categoryImageUrl: "mattresses.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
    ],
  },
  {
    id: 39,
    categoryName: "Grocery",
    urlSlug: "grocery",
    parentCategoryId: null,
    level: "COLLECTION",
    categoryImageUrl: "grocery.jpg",
    status: "ACTIVE",
    createdAt: "2024-08-25",
    updatedAt: null,
    subCategories: [
      {
        id: 40,
        categoryName: "Fruits & Vegetables",
        urlSlug: "fruits-vegetables",
        parentCategoryId: 39,
        level: "CATEGORY",
        categoryImageUrl: "fruits-vegetables.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 41,
            categoryName: "Fresh Fruits",
            urlSlug: "fresh-fruits",
            parentCategoryId: 40,
            level: "SUB_CATEGORY",
            categoryImageUrl: "fresh-fruits.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 42,
            categoryName: "Fresh Vegetables",
            urlSlug: "fresh-vegetables",
            parentCategoryId: 40,
            level: "SUB_CATEGORY",
            categoryImageUrl: "fresh-vegetables.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 43,
            categoryName: "Herbs & Seasonings",
            urlSlug: "herbs-seasonings",
            parentCategoryId: 40,
            level: "SUB_CATEGORY",
            categoryImageUrl: "herbs-seasonings.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 44,
            categoryName: "Exotic Fruits",
            urlSlug: "exotic-fruits",
            parentCategoryId: 40,
            level: "SUB_CATEGORY",
            categoryImageUrl: "exotic-fruits.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 45,
            categoryName: "Organic Vegetables",
            urlSlug: "organic-vegetables",
            parentCategoryId: 40,
            level: "SUB_CATEGORY",
            categoryImageUrl: "organic-vegetables.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 46,
        categoryName: "Dairy & Eggs",
        urlSlug: "dairy-eggs",
        parentCategoryId: 39,
        level: "CATEGORY",
        categoryImageUrl: "dairy-eggs.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 47,
            categoryName: "Milk",
            urlSlug: "milk",
            parentCategoryId: 46,
            level: "SUB_CATEGORY",
            categoryImageUrl: "milk.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 48,
            categoryName: "Cheese",
            urlSlug: "cheese",
            parentCategoryId: 46,
            level: "SUB_CATEGORY",
            categoryImageUrl: "cheese.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 49,
            categoryName: "Butter",
            urlSlug: "butter",
            parentCategoryId: 46,
            level: "SUB_CATEGORY",
            categoryImageUrl: "butter.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 50,
            categoryName: "Yogurt",
            urlSlug: "yogurt",
            parentCategoryId: 46,
            level: "SUB_CATEGORY",
            categoryImageUrl: "yogurt.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 51,
            categoryName: "Eggs",
            urlSlug: "eggs",
            parentCategoryId: 46,
            level: "SUB_CATEGORY",
            categoryImageUrl: "eggs.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 52,
        categoryName: "Beverages",
        urlSlug: "beverages",
        parentCategoryId: 39,
        level: "CATEGORY",
        categoryImageUrl: "beverages.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 53,
            categoryName: "Juices",
            urlSlug: "juices",
            parentCategoryId: 52,
            level: "SUB_CATEGORY",
            categoryImageUrl: "juices.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 54,
            categoryName: "Soft Drinks",
            urlSlug: "soft-drinks",
            parentCategoryId: 52,
            level: "SUB_CATEGORY",
            categoryImageUrl: "soft-drinks.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 55,
            categoryName: "Energy Drinks",
            urlSlug: "energy-drinks",
            parentCategoryId: 52,
            level: "SUB_CATEGORY",
            categoryImageUrl: "energy-drinks.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 56,
            categoryName: "Tea & Coffee",
            urlSlug: "tea-coffee",
            parentCategoryId: 52,
            level: "SUB_CATEGORY",
            categoryImageUrl: "tea-coffee.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 57,
            categoryName: "Alcoholic Beverages",
            urlSlug: "alcoholic-beverages",
            parentCategoryId: 52,
            level: "SUB_CATEGORY",
            categoryImageUrl: "alcoholic-beverages.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
    ],
  },
  {
    id: 58,
    categoryName: "Sports & Outdoor",
    urlSlug: "sports-outdoor",
    parentCategoryId: null,
    level: "COLLECTION",
    categoryImageUrl: "sports-outdoor.jpg",
    status: "ACTIVE",
    createdAt: "2024-08-25",
    updatedAt: null,
    subCategories: [
      {
        id: 59,
        categoryName: "Outdoor Sports",
        urlSlug: "outdoor-sports",
        parentCategoryId: 58,
        level: "CATEGORY",
        categoryImageUrl: "outdoor-sports.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 60,
            categoryName: "Camping",
            urlSlug: "camping",
            parentCategoryId: 59,
            level: "SUB_CATEGORY",
            categoryImageUrl: "camping.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 61,
            categoryName: "Hiking",
            urlSlug: "hiking",
            parentCategoryId: 59,
            level: "SUB_CATEGORY",
            categoryImageUrl: "hiking.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 62,
            categoryName: "Cycling",
            urlSlug: "cycling",
            parentCategoryId: 59,
            level: "SUB_CATEGORY",
            categoryImageUrl: "cycling.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 63,
            categoryName: "Fishing",
            urlSlug: "fishing",
            parentCategoryId: 59,
            level: "SUB_CATEGORY",
            categoryImageUrl: "fishing.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 64,
            categoryName: "Climbing",
            urlSlug: "climbing",
            parentCategoryId: 59,
            level: "SUB_CATEGORY",
            categoryImageUrl: "climbing.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 65,
        categoryName: "Fitness",
        urlSlug: "fitness",
        parentCategoryId: 58,
        level: "CATEGORY",
        categoryImageUrl: "fitness.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 66,
            categoryName: "Exercise Equipment",
            urlSlug: "exercise-equipment",
            parentCategoryId: 65,
            level: "SUB_CATEGORY",
            categoryImageUrl: "exercise-equipment.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 67,
            categoryName: "Yoga & Pilates",
            urlSlug: "yoga-pilates",
            parentCategoryId: 65,
            level: "SUB_CATEGORY",
            categoryImageUrl: "yoga-pilates.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 68,
            categoryName: "Strength Training",
            urlSlug: "strength-training",
            parentCategoryId: 65,
            level: "SUB_CATEGORY",
            categoryImageUrl: "strength-training.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 69,
            categoryName: "Cardio",
            urlSlug: "cardio",
            parentCategoryId: 65,
            level: "SUB_CATEGORY",
            categoryImageUrl: "cardio.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 70,
            categoryName: "Sports Nutrition",
            urlSlug: "sports-nutrition",
            parentCategoryId: 65,
            level: "SUB_CATEGORY",
            categoryImageUrl: "sports-nutrition.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 71,
        categoryName: "Team Sports",
        urlSlug: "team-sports",
        parentCategoryId: 58,
        level: "CATEGORY",
        categoryImageUrl: "team-sports.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 72,
            categoryName: "Football",
            urlSlug: "football",
            parentCategoryId: 71,
            level: "SUB_CATEGORY",
            categoryImageUrl: "football.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 73,
            categoryName: "Basketball",
            urlSlug: "basketball",
            parentCategoryId: 71,
            level: "SUB_CATEGORY",
            categoryImageUrl: "basketball.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 74,
            categoryName: "Baseball",
            urlSlug: "baseball",
            parentCategoryId: 71,
            level: "SUB_CATEGORY",
            categoryImageUrl: "baseball.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 75,
            categoryName: "Volleyball",
            urlSlug: "volleyball",
            parentCategoryId: 71,
            level: "SUB_CATEGORY",
            categoryImageUrl: "volleyball.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 76,
            categoryName: "Hockey",
            urlSlug: "hockey",
            parentCategoryId: 71,
            level: "SUB_CATEGORY",
            categoryImageUrl: "hockey.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
    ],
  },
  {
    id: 77,
    categoryName: "Electronics",
    urlSlug: "electronics",
    parentCategoryId: null,
    level: "COLLECTION",
    categoryImageUrl: "electronics.jpg",
    status: "ACTIVE",
    createdAt: "2024-08-25",
    updatedAt: null,
    subCategories: [
      {
        id: 78,
        categoryName: "Computer Accessories",
        urlSlug: "computer-accessories",
        parentCategoryId: 77,
        level: "CATEGORY",
        categoryImageUrl: "computer-accessories.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 79,
            categoryName: "Keyboards",
            urlSlug: "keyboards",
            parentCategoryId: 78,
            level: "SUB_CATEGORY",
            categoryImageUrl: "keyboards.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 80,
            categoryName: "Mice",
            urlSlug: "mice",
            parentCategoryId: 78,
            level: "SUB_CATEGORY",
            categoryImageUrl: "mice.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 81,
            categoryName: "Monitors",
            urlSlug: "monitors",
            parentCategoryId: 78,
            level: "SUB_CATEGORY",
            categoryImageUrl: "monitors.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 82,
            categoryName: "PC Audio",
            urlSlug: "pc-audio",
            parentCategoryId: 78,
            level: "SUB_CATEGORY",
            categoryImageUrl: "pc-audio.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 83,
            categoryName: "Storage",
            urlSlug: "storage",
            parentCategoryId: 78,
            level: "SUB_CATEGORY",
            categoryImageUrl: "storage.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 84,
        categoryName: "Camera Accessories",
        urlSlug: "camera-accessories",
        parentCategoryId: 78,
        level: "CATEGORY",
        categoryImageUrl: "camera-accessories.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 85,
            categoryName: "Lenses",
            urlSlug: "lenses",
            parentCategoryId: 84,
            level: "SUB_CATEGORY",
            categoryImageUrl: "lenses.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 86,
            categoryName: "Camera Bags",
            urlSlug: "camera-bags",
            parentCategoryId: 84,
            level: "SUB_CATEGORY",
            categoryImageUrl: "camera-bags.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 87,
            categoryName: "Tripods",
            urlSlug: "tripods",
            parentCategoryId: 84,
            level: "SUB_CATEGORY",
            categoryImageUrl: "tripods.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 88,
            categoryName: "Batteries & Chargers",
            urlSlug: "batteries-chargers",
            parentCategoryId: 84,
            level: "SUB_CATEGORY",
            categoryImageUrl: "batteries-chargers.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 89,
            categoryName: "Memory Cards",
            urlSlug: "memory-cards",
            parentCategoryId: 84,
            level: "SUB_CATEGORY",
            categoryImageUrl: "memory-cards.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
      {
        id: 90,
        categoryName: "Gadgets",
        urlSlug: "gadgets",
        parentCategoryId: 77,
        level: "CATEGORY",
        categoryImageUrl: "gadgets.jpg",
        status: "ACTIVE",
        createdAt: "2024-08-25",
        updatedAt: null,
        subCategories: [
          {
            id: 91,
            categoryName: "Smartwatches",
            urlSlug: "smartwatches",
            parentCategoryId: 90,
            level: "SUB_CATEGORY",
            categoryImageUrl: "smartwatches.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 92,
            categoryName: "Fitness Trackers",
            urlSlug: "fitness-trackers",
            parentCategoryId: 90,
            level: "SUB_CATEGORY",
            categoryImageUrl: "fitness-trackers.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 93,
            categoryName: "Drones",
            urlSlug: "drones",
            parentCategoryId: 90,
            level: "SUB_CATEGORY",
            categoryImageUrl: "drones.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 94,
            categoryName: "VR Headsets",
            urlSlug: "vr-headsets",
            parentCategoryId: 90,
            level: "SUB_CATEGORY",
            categoryImageUrl: "vr-headsets.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
          {
            id: 95,
            categoryName: "Portable Speakers",
            urlSlug: "portable-speakers",
            parentCategoryId: 90,
            level: "SUB_CATEGORY",
            categoryImageUrl: "portable-speakers.jpg",
            status: "ACTIVE",
            createdAt: "2024-08-25",
            updatedAt: null,
          },
        ],
      },
    ],
  },
];
